package resources

var (
	MESSAGECENTER = "MESSAGECENTER"
	CLIENTSECRET = "CLIENTSECRET"
	CLIENTID = "CLIENTID"
	APPLYMSGTYPE = "APPLYMSGTYPE"
	SERVERPORT = "SERVERPORT"
	CHANNELS = "CHANNELS"
	RECEIVERS = "RECEIVERS"
)
