// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/gzlj/message-agent-operator/pkg/apis/messageagent/v1.MessageAgent":       schema_pkg_apis_messageagent_v1_MessageAgent(ref),
		"github.com/gzlj/message-agent-operator/pkg/apis/messageagent/v1.MessageAgentSpec":   schema_pkg_apis_messageagent_v1_MessageAgentSpec(ref),
		"github.com/gzlj/message-agent-operator/pkg/apis/messageagent/v1.MessageAgentStatus": schema_pkg_apis_messageagent_v1_MessageAgentStatus(ref),
	}
}

func schema_pkg_apis_messageagent_v1_MessageAgent(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MessageAgent is the Schema for the messageagents API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gzlj/message-agent-operator/pkg/apis/messageagent/v1.MessageAgentSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gzlj/message-agent-operator/pkg/apis/messageagent/v1.MessageAgentStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/gzlj/message-agent-operator/pkg/apis/messageagent/v1.MessageAgentSpec", "github.com/gzlj/message-agent-operator/pkg/apis/messageagent/v1.MessageAgentStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_messageagent_v1_MessageAgentSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MessageAgentSpec defines the desired state of MessageAgent",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_messageagent_v1_MessageAgentStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MessageAgentStatus defines the observed state of MessageAgent",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
